//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Movement/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""PlayerAboveIsometric"",
            ""id"": ""4dc86be0-2f52-48da-b6b7-4d6a8a1c29ff"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""747b86da-8f51-478b-8989-7298e5d18669"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""11339f36-d0f1-46e2-9af6-faa1be024714"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""24813581-18f1-4825-9cd1-a75ad1ddd737"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e5df21c8-849d-4247-aebf-097c607982c5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ffd71582-9053-4a84-91f8-b96045317110"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""15233af5-b24e-436b-8234-1e924bb8197e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerSide"",
            ""id"": ""c95998c7-f41c-4d6d-94c9-eb0488cac497"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""21511369-8fac-49e7-a94d-af6697ef6c96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bc873628-079a-4228-b321-13ba8c40cac5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""71da1ae0-919c-4e37-88ee-db0224c7e819"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7a65f27e-f70d-43cd-88ae-9756bfa9e7b9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d6761d78-8d8c-44ed-b5d5-83cd2b57b224"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c5a31934-2ca5-4907-a38c-e7b97b6dc2c2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerAboveIsometric
        m_PlayerAboveIsometric = asset.FindActionMap("PlayerAboveIsometric", throwIfNotFound: true);
        m_PlayerAboveIsometric_Move = m_PlayerAboveIsometric.FindAction("Move", throwIfNotFound: true);
        // PlayerSide
        m_PlayerSide = asset.FindActionMap("PlayerSide", throwIfNotFound: true);
        m_PlayerSide_Jump = m_PlayerSide.FindAction("Jump", throwIfNotFound: true);
        m_PlayerSide_Move = m_PlayerSide.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerAboveIsometric
    private readonly InputActionMap m_PlayerAboveIsometric;
    private List<IPlayerAboveIsometricActions> m_PlayerAboveIsometricActionsCallbackInterfaces = new List<IPlayerAboveIsometricActions>();
    private readonly InputAction m_PlayerAboveIsometric_Move;
    public struct PlayerAboveIsometricActions
    {
        private @Player m_Wrapper;
        public PlayerAboveIsometricActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerAboveIsometric_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAboveIsometric; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerAboveIsometricActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerAboveIsometricActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerAboveIsometricActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerAboveIsometricActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerAboveIsometricActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerAboveIsometricActions instance)
        {
            if (m_Wrapper.m_PlayerAboveIsometricActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerAboveIsometricActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerAboveIsometricActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerAboveIsometricActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerAboveIsometricActions @PlayerAboveIsometric => new PlayerAboveIsometricActions(this);

    // PlayerSide
    private readonly InputActionMap m_PlayerSide;
    private List<IPlayerSideActions> m_PlayerSideActionsCallbackInterfaces = new List<IPlayerSideActions>();
    private readonly InputAction m_PlayerSide_Jump;
    private readonly InputAction m_PlayerSide_Move;
    public struct PlayerSideActions
    {
        private @Player m_Wrapper;
        public PlayerSideActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_PlayerSide_Jump;
        public InputAction @Move => m_Wrapper.m_PlayerSide_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerSide; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerSideActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerSideActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerSideActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerSideActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerSideActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerSideActions instance)
        {
            if (m_Wrapper.m_PlayerSideActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerSideActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerSideActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerSideActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerSideActions @PlayerSide => new PlayerSideActions(this);
    public interface IPlayerAboveIsometricActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IPlayerSideActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
